# Generated by Django 3.1.1 on 2020-09-10 23:48

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200910_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='activity',
            field=models.ForeignKey(help_text='Activity like Devlopment, Testing..', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.activity'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='end_time',
            field=models.DateTimeField(validators=[core.models.validate_end_time]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_time',
            field=models.DateTimeField(validators=[core.models.validate_start_time]),
        ),
    ]
