# Generated by Django 3.1.1 on 2020-09-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200911_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.CharField(help_text="Enter a short code. For Ex-'Dev' for Development", max_length=5, unique=True),
        ),
    ]
